<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FundingProgram;

class FundingProgramsSeeder extends Seeder
{
    public function run(): void
    {
        $programs = [
            [
                'name' => 'Startup India Seed Fund Scheme (SISFS)',
                'slug' => 'startup-india-seed-fund-scheme',
                'organization_name' => 'Department for Promotion of Industry and Internal Trade (DPIIT)',
                'organization_logo' => 'https://ui-avatars.com/api/?name=Startup+India&background=0B1F3A&color=D4A843&bold=true',
                'funding_amount' => '₹50 Lakhs',
                'funding_amount_numeric' => 5000000.00,
                'country' => 'India',
                'industry' => 'Multi-Sector (Tech, FinTech, AgriTech, CleanTech)',
                'funding_type' => 'Government',
                'startup_stage' => 'MVP',
                'short_description' => 'Financial assistance to startups for proof of concept, prototype development, product trials, market entry, and commercialization.',
                'description' => 'The Startup India Seed Fund Scheme (SISFS) aims to provide financial assistance to early-stage startups. Funding up to ₹20 Lakhs as a grant for validation of Proof of Concept, and up to ₹50 Lakhs of investment for prototype development or product commercialization through convertible debentures or debt.',
                'eligibility' => "1. Recognized by DPIIT\n2. Incorporated not more than 2 years prior to application date\n3. Must have a business idea to develop a product or service with market fit.",
                'required_documents' => "1. DPIIT Certificate\n2. Pitch Deck (PDF)\n3. Certificate of Incorporation\n4. Founders' ID proof",
                'application_deadline' => '2026-12-31',
                'official_apply_url' => 'https://seedfund.startupindia.gov.in/',
                'is_featured' => true,
                'priority' => 10,
                'status' => 'active',
                'seo_title' => 'Startup India Seed Fund Scheme (SISFS) 2026 - Apply for ₹50L Grant',
                'seo_description' => 'Apply for DPIIT Startup India Seed Fund Scheme. Get up to ₹50 Lakhs grant and debt funding for prototype and market entry.',
                'meta_keywords' => 'Startup India, SISFS, Government Grant, DPIIT Funding, Seed Fund India',
            ],
            [
                'name' => 'NITI Aayog Women Entrepreneurship Platform (WEP) Grant',
                'slug' => 'niti-aayog-women-entrepreneurship-grant',
                'organization_name' => 'NITI Aayog & Government of India',
                'organization_logo' => 'https://ui-avatars.com/api/?name=NITI+Aayog&background=0B1F3A&color=D4A843&bold=true',
                'funding_amount' => '₹25 Lakhs',
                'funding_amount_numeric' => 2500000.00,
                'country' => 'India',
                'industry' => 'Women-Led Startups, Social Impact, EdTech',
                'funding_type' => 'Grant',
                'startup_stage' => 'Early Stage',
                'short_description' => 'Special government grant empowering women founders across India with capital, mentorship, and enterprise acceleration.',
                'description' => 'NITI Aayog WEP offers dedicated financial grants up to ₹25 Lakhs along with incubation support, legal guidance, and corporate partnership access to female founders building scalable ventures.',
                'eligibility' => "1. At least 51% equity owned by female founder(s)\n2. Operating in India\n3. Registered entity (Pvt Ltd, LLP, or Partnership)",
                'required_documents' => "1. Pitch Deck\n2. Financial Projections\n3. Company Registration Copy\n4. Aadhaar & PAN of Female Founder",
                'application_deadline' => '2026-10-15',
                'official_apply_url' => 'https://wep.gov.in/',
                'is_featured' => true,
                'priority' => 9,
                'status' => 'active',
                'seo_title' => 'NITI Aayog Women Entrepreneurship Grant - Up to ₹25L Funding',
                'seo_description' => 'Special Government Grant for Women Entrepreneurs in India. Get up to ₹25 Lakhs capital and NITI Aayog mentorship.',
                'meta_keywords' => 'NITI Aayog Grant, Women Startup Fund, Female Founder India, Government Grant',
            ],
            [
                'name' => 'Y Combinator Accelerator Program (S26 Batch)',
                'slug' => 'y-combinator-s26-accelerator',
                'organization_name' => 'Y Combinator (YC)',
                'organization_logo' => 'https://ui-avatars.com/api/?name=Y+Combinator&background=FF6600&color=FFFFFF&bold=true',
                'funding_amount' => '$500,000 (~₹4.1 Cr)',
                'funding_amount_numeric' => 41000000.00,
                'country' => 'Global',
                'industry' => 'SaaS, AI, Fintech, BioTech, Consumer',
                'funding_type' => 'Accelerator',
                'startup_stage' => 'Idea',
                'short_description' => '$500k total investment for 7% post-money SAFE + MFN SAFE. 3-month intensive Silicon Valley accelerator.',
                'description' => 'Y Combinator invests $500,000 in early-stage companies twice a year. We work closely with founders for 3 months to refine their pitch, build product traction, and present to top global investors on Demo Day.',
                'eligibility' => "1. Founders from any country\n2. Technical or non-technical co-founders\n3. Pre-seed or seed stage startups",
                'required_documents' => "1. Video Introduction (1 min)\n2. Online YC Application form\n3. Product Demo Video\n4. Pitch Deck",
                'application_deadline' => '2026-09-30',
                'official_apply_url' => 'https://www.ycombinator.com/apply',
                'is_featured' => true,
                'priority' => 10,
                'status' => 'active',
                'seo_title' => 'Y Combinator S26 Acceleration - $500,000 Global Startup Funding',
                'seo_description' => 'Apply for Y Combinator $500,000 funding and 3-month Silicon Valley acceleration program.',
                'meta_keywords' => 'Y Combinator, YC S26, Silicon Valley Funding, Seed Capital, Global Accelerator',
            ],
            [
                'name' => 'Sequoia Surge Scale-Up Program',
                'slug' => 'sequoia-surge-program',
                'organization_name' => 'Peak XV Partners (Formerly Sequoia India)',
                'organization_logo' => 'https://ui-avatars.com/api/?name=Peak+XV&background=0B1F3A&color=D4A843&bold=true',
                'funding_amount' => '$1,000,000 - $3,000,000',
                'funding_amount_numeric' => 150000000.00,
                'country' => 'India',
                'industry' => 'AI, Consumer, FinTech, HealthTech, Enterprise Software',
                'funding_type' => 'VC',
                'startup_stage' => 'Early Stage',
                'short_description' => 'Up to $3M seed capital, intensive mentorship modules, and access to top global founders community.',
                'description' => 'Surge combines up to $3M of seed capital with company-building workshops, global immersion trips, and direct mentorship from world-class tech founders.',
                'eligibility' => "1. Early stage companies based in India & SEA\n2. High growth potential with strong founding team",
                'required_documents' => "1. Pitch Deck\n2. Cap Table\n3. Traction Metrics / Financials",
                'application_deadline' => '2026-11-01',
                'official_apply_url' => 'https://www.surgeahead.com/',
                'is_featured' => false,
                'priority' => 8,
                'status' => 'active',
                'seo_title' => 'Peak XV Surge Program - Up to $3M VC Funding for Indian Startups',
                'seo_description' => 'Get up to $3 Million seed investment from Peak XV Surge for Indian and Southeast Asian startups.',
                'meta_keywords' => 'Peak XV, Surge, Venture Capital, VC Fund India, Seed Investment',
            ],
            [
                'name' => 'BIRAC BIG (Biotechnology Ignition Grant)',
                'slug' => 'birac-big-grant',
                'organization_name' => 'Biotechnology Industry Research Assistance Council (BIRAC)',
                'organization_logo' => 'https://ui-avatars.com/api/?name=BIRAC&background=0B1F3A&color=D4A843&bold=true',
                'funding_amount' => '₹50 Lakhs',
                'funding_amount_numeric' => 5000000.00,
                'country' => 'India',
                'industry' => 'Biotech, HealthTech, MedTech, AgriTech',
                'funding_type' => 'Grant',
                'startup_stage' => 'Idea',
                'short_description' => 'Government grant for biotech innovators to establish proof-of-concept for commercializable research ideas.',
                'description' => 'BIRAC BIG scheme enables researchers, scientists, and biotech entrepreneurs to develop innovative biotech & healthcare products into commercialized startups.',
                'eligibility' => "1. Indian Biotech startups / individuals\n2. Entity age less than 5 years\n3. Novel biotech innovation",
                'required_documents' => "1. Detailed Project Proposal\n2. Intellectual Property details\n3. Entity Registration",
                'application_deadline' => '2026-08-31',
                'official_apply_url' => 'https://birac.nic.in/',
                'is_featured' => false,
                'priority' => 7,
                'status' => 'active',
                'seo_title' => 'BIRAC BIG Grant 2026 - ₹50 Lakhs Biotech Funding',
                'seo_description' => 'Apply for BIRAC Biotechnology Ignition Grant. Up to ₹50 Lakhs non-dilutive grant for healthcare and biotech innovation.',
                'meta_keywords' => 'BIRAC BIG Grant, HealthTech Grant, Biotech Funding India, Non-dilutive Grant',
            ]
        ];

        foreach ($programs as $prog) {
            FundingProgram::updateOrCreate(['slug' => $prog['slug']], $prog);
        }
    }
}
